### Create a course
POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "SGVsbG8gQ291cnNl",         // Base64 for "Hello Course"
  "description": "QmVnaW5uZXIgbGV2ZWw=", // Base64 for "Beginner level"
  "institutionAddress": "0xInstitution123",
  "price": 1000,
  "createdAt": 1714693200,
  "metadata": "eyJrZXkiOiAidmFsdWUifQ=="  // Base64 for '{"key": "value"}'
}

### Get all courses
GET http://localhost:3000/courses

### Get a single course
GET http://localhost:3000/courses/1

### Update a course
PUT http://localhost:3000/courses/1
Content-Type: application/json

{
  "price": 1200,
  "description": "VXBkYXRlZCBsZXZlbA==" // Base64 for "Updated level"
}

### Delete a course
DELETE http://localhost:3000/courses/1
